import subprocess
import sys
import tempfile
import textwrap
import unittest
from pathlib import Path


SCRIPT_PATH = Path(__file__).resolve().parents[1] / "scripts" / "init_leetcode_problem.py"


ARRAY_PROBLEM_TEXT = textwrap.dedent(
    """
    You are given an integer array nums of length n, and an integer array queries of length m.

    Return an array answer of length m where answer[i] is the maximum size of a subsequence that you can take from nums such that the sum of its elements is less than or equal to queries[i].

    A subsequence is an array that can be derived from another array by deleting some or no elements without changing the order of the remaining elements.

    Example 1:
    Input: nums = [4,5,2,1], queries = [3,10,21]
    Output: [2,3,4]
    Explanation: Example explanation.

    Example 2:
    Input: nums = [2,3,4,5], queries = [1]
    Output: [0]
    """
).strip()


TREE_PROBLEM_TEXT = textwrap.dedent(
    """
    Example 1:
    Input: root = [1,null,2,3]
    Output: [1,3,2]
    """
).strip()


LIST_PROBLEM_TEXT = textwrap.dedent(
    """
    Example 1:
    Input: head = [1,2,3,4]
    Output: [1,2,3,4]
    """
).strip()


class LeetCodeInitScriptTestCase(unittest.TestCase):
    """Verify scaffold generation and rewrite safety for the LeetCode initializer."""

    def setUp(self):
        """Create an isolated workspace for each initializer test."""
        self.tmpdir = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmpdir.cleanup)
        self.workspace = Path(self.tmpdir.name)

    def write_pair(self, slug: str, text_content: str, python_content: str) -> Path:
        """Write a same-name `.txt`/`.py` problem pair into the temp workspace."""
        text_path = self.workspace / f"{slug}.txt"
        python_path = self.workspace / f"{slug}.py"
        text_path.write_text(text_content + "\n", encoding="utf-8")
        python_path.write_text(python_content, encoding="utf-8")
        return python_path

    def run_script(self, target: Path):
        """Execute the initializer script against a target problem path."""
        return subprocess.run(
            [sys.executable, str(SCRIPT_PATH), str(target)],
            capture_output=True,
            text=True,
            cwd=self.workspace,
        )

    def test_generates_runner_and_unittest_for_array_examples(self):
        """Generate the default scaffold for a plain list-based problem."""
        python_path = self.write_pair(
            "longest-subsequence-with-limited-sum",
            ARRAY_PROBLEM_TEXT,
            textwrap.dedent(
                """
                from typing import List

                class Solution:
                    def answerQueries(self, nums: List[int], queries: List[int]) -> List[int]:
                        
                """
            ).lstrip(),
        )

        result = self.run_script(python_path)

        self.assertEqual(0, result.returncode, msg=result.stderr or result.stdout)
        generated = python_path.read_text(encoding="utf-8")
        self.assertIn("# Generated by leetcode-init", generated)
        self.assertIn("EXAMPLES =", generated)
        self.assertIn("def run_examples()", generated)
        self.assertIn("class GeneratedExampleTests(unittest.TestCase):", generated)
        self.assertIn("raise NotImplementedError", generated)
        self.assertIn("Example 1", generated)
        self.assertIn("Example 2", generated)
        self.assertIn(
            "You are given an integer array nums of length n, and an integer array",
            generated,
        )
        self.assertIn(
            "queries of length m.",
            generated,
        )
        self.assertIn(
            "Return an array answer of length m where answer[i] is the maximum size",
            generated,
        )
        self.assertIn(
            "of a subsequence that you can take from nums such that the sum of its",
            generated,
        )
        self.assertIn(
            "A subsequence is an array that can be derived from another array by",
            generated,
        )
        self.assertIn('        Examples:', generated)
        self.assertIn("Example 1", generated)
        self.assertIn("Input: nums = [4, 5, 2, 1], queries = [3, 10, 21]", generated)
        self.assertIn("Output: [2, 3, 4]", generated)
        self.assertIn("Example 2", generated)
        self.assertIn("Input: nums = [2, 3, 4, 5], queries = [1]", generated)
        self.assertIn("Output: [0]", generated)
        self.assertIn('    """Convert one stored example input into the expected runtime value."""', generated)
        self.assertIn('    """Normalize a solution result back into comparable plain data."""', generated)
        self.assertIn('    """Render a unified diff for mismatched expected and actual values."""', generated)
        self.assertIn('    """Execute one example case and capture any failure mode."""', generated)
        self.assertIn('    """Print each parsed example and compare it against the current solution."""', generated)
        self.assertIn('        """Assert that every parsed example matches the current solution output."""', generated)
        self.assertIn('    """Run the generated CLI entrypoint for examples or unittest mode."""', generated)
        docstring_lines = []
        in_docstring = False
        for line in generated.splitlines():
            if '        """' in line and not in_docstring:
                in_docstring = True
            if in_docstring:
                docstring_lines.append(line)
            if in_docstring and line.strip() == '"""':
                break
        self.assertTrue(docstring_lines)
        self.assertTrue(all(len(line) <= 79 for line in docstring_lines), msg=docstring_lines)
        self.assertIn("---", result.stdout)

        run_result = subprocess.run(
            [sys.executable, str(python_path)],
            capture_output=True,
            text=True,
            cwd=self.workspace,
        )
        self.assertEqual(0, run_result.returncode, msg=run_result.stderr)
        self.assertIn("not implemented", run_result.stdout.lower())
        self.assertIn("Input:", run_result.stdout)
        self.assertIn("{'nums': [4, 5, 2, 1], 'queries': [3, 10, 21]}", run_result.stdout)
        self.assertIn("{'nums': [2, 3, 4, 5], 'queries': [1]}", run_result.stdout)
        self.assertIn("Expected:", run_result.stdout)

    def test_generates_tree_helpers_when_tree_nodes_are_used(self):
        """Add tree helpers only when the parsed signature uses `TreeNode`."""
        python_path = self.write_pair(
            "binary-tree-inorder-traversal",
            TREE_PROBLEM_TEXT,
            textwrap.dedent(
                """
                from typing import List, Optional

                class Solution:
                    def inorderTraversal(self, root: Optional[TreeNode]) -> List[int]:
                        
                """
            ).lstrip(),
        )

        result = self.run_script(python_path)

        self.assertEqual(0, result.returncode, msg=result.stderr or result.stdout)
        generated = python_path.read_text(encoding="utf-8")
        self.assertIn("class TreeNode:", generated)
        self.assertIn('    """Create a binary tree node used by LeetCode examples."""', generated)
        self.assertIn("def build_tree(", generated)
        self.assertIn('    """Build a binary tree from LeetCode level-order list data."""', generated)
        self.assertIn('    """Convert a binary tree back into LeetCode level-order list data."""', generated)
        self.assertNotIn("class ListNode:", generated)

    def test_generates_list_helpers_when_linked_lists_are_used(self):
        """Add linked-list helpers only when the parsed signature uses `ListNode`."""
        python_path = self.write_pair(
            "reverse-linked-list",
            LIST_PROBLEM_TEXT,
            textwrap.dedent(
                """
                from typing import Optional

                class Solution:
                    def reverseList(self, head: Optional[ListNode]) -> Optional[ListNode]:
                        
                """
            ).lstrip(),
        )

        result = self.run_script(python_path)

        self.assertEqual(0, result.returncode, msg=result.stderr or result.stdout)
        generated = python_path.read_text(encoding="utf-8")
        self.assertIn("class ListNode:", generated)
        self.assertIn('    """Create a linked-list node used by LeetCode examples."""', generated)
        self.assertIn("def build_linked_list(", generated)
        self.assertIn("def serialize_linked_list(", generated)
        self.assertIn('    """Build a linked list from LeetCode list input data."""', generated)
        self.assertIn('    """Convert a linked list back into plain Python list data."""', generated)
        self.assertNotIn("class TreeNode:", generated)

    def test_preserves_existing_solution_docstring(self):
        """Keep a user-authored solution docstring during scaffold generation."""
        python_path = self.write_pair(
            "contains-duplicate",
            ARRAY_PROBLEM_TEXT,
            textwrap.dedent(
                '''
                from typing import List

                class Solution:
                    def containsDuplicate(self, nums: List[int]) -> bool:
                        """Return whether any value appears at least twice."""
                        ...
                '''
            ).lstrip(),
        )

        result = self.run_script(python_path)

        self.assertEqual(0, result.returncode, msg=result.stderr or result.stdout)
        generated = python_path.read_text(encoding="utf-8")
        self.assertIn('"""Return whether any value appears at least twice."""', generated)
        self.assertNotIn('"""Examples:', generated)

    def test_refuses_to_overwrite_non_stub_solution_file(self):
        """Reject initialization when the original stub already has real logic."""
        python_path = self.write_pair(
            "two-sum",
            ARRAY_PROBLEM_TEXT,
            textwrap.dedent(
                """
                from typing import List

                class Solution:
                    def twoSum(self, nums: List[int], target: int) -> List[int]:
                        seen = {}
                        for index, num in enumerate(nums):
                            if target - num in seen:
                                return [seen[target - num], index]
                            seen[num] = index
                        return []
                """
            ).lstrip(),
        )

        result = self.run_script(python_path)

        self.assertNotEqual(0, result.returncode)
        self.assertIn("Refusing to overwrite", result.stderr)

    def test_is_idempotent_for_generated_scaffold(self):
        """Leave a freshly generated scaffold unchanged on a second run."""
        python_path = self.write_pair(
            "merge-two-sorted-lists",
            LIST_PROBLEM_TEXT,
            textwrap.dedent(
                """
                from typing import Optional

                class Solution:
                    def mergeTwoLists(self, list1: Optional[ListNode], list2: Optional[ListNode]) -> Optional[ListNode]:
                        
                """
            ).lstrip(),
        )

        first_result = self.run_script(python_path)
        self.assertEqual(0, first_result.returncode, msg=first_result.stderr or first_result.stdout)
        first_content = python_path.read_text(encoding="utf-8")

        second_result = self.run_script(python_path)
        self.assertEqual(0, second_result.returncode, msg=second_result.stderr or second_result.stdout)
        second_content = python_path.read_text(encoding="utf-8")

        self.assertEqual(first_content, second_content)
        self.assertEqual(1, second_content.count("# Generated by leetcode-init"))

    def test_reinitialize_preserves_existing_solution_code(self):
        """Preserve user solution code when re-initializing a generated scaffold."""
        python_path = self.write_pair(
            "preserve-solution",
            ARRAY_PROBLEM_TEXT,
            textwrap.dedent(
                """
                from typing import List

                class Solution:
                    def answerQueries(self, nums: List[int], queries: List[int]) -> List[int]:
                        
                """
            ).lstrip(),
        )

        first_result = self.run_script(python_path)
        self.assertEqual(0, first_result.returncode, msg=first_result.stderr or first_result.stdout)

        generated = python_path.read_text(encoding="utf-8")
        updated = generated.replace(
            '        raise NotImplementedError("Implement answerQueries before running this scaffold.")',
            "        return [len(nums)] * len(queries)",
        )
        python_path.write_text(updated, encoding="utf-8")

        second_result = self.run_script(python_path)

        self.assertEqual(0, second_result.returncode, msg=second_result.stderr or second_result.stdout)
        preserved = python_path.read_text(encoding="utf-8")
        self.assertIn("return [len(nums)] * len(queries)", preserved)
        self.assertNotIn("raise NotImplementedError", preserved)

    def test_reinitialize_replaces_generated_placeholder_docstring(self):
        """Replace the old generated placeholder docstring with example details."""
        python_path = self.write_pair(
            "replace-generated-docstring",
            ARRAY_PROBLEM_TEXT,
            textwrap.dedent(
                '''
                from typing import List

                class Solution:
                    def answerQueries(self, nums: List[int], queries: List[int]) -> List[int]:
                        """Solve the LeetCode problem for the provided inputs."""
                        raise NotImplementedError("Implement answerQueries before running this scaffold.")
                '''
            ).lstrip(),
        )

        result = self.run_script(python_path)

        self.assertEqual(0, result.returncode, msg=result.stderr or result.stdout)
        generated = python_path.read_text(encoding="utf-8")
        self.assertNotIn('"""Solve the LeetCode problem for the provided inputs."""', generated)
        self.assertIn("Examples:", generated)
        self.assertIn("Input: nums = [4, 5, 2, 1], queries = [3, 10, 21]", generated)
        self.assertIn("Output: [2, 3, 4]", generated)

    def test_fails_when_text_file_has_no_examples(self):
        """Report a clear error when the prompt dump does not include examples."""
        python_path = self.write_pair(
            "empty-problem",
            "Problem statement with no examples.\n",
            textwrap.dedent(
                """
                class Solution:
                    def doThing(self, value: int) -> int:
                        
                """
            ).lstrip(),
        )

        result = self.run_script(python_path)

        self.assertNotEqual(0, result.returncode)
        self.assertIn("No examples found", result.stderr)


if __name__ == "__main__":
    unittest.main()
