#!/usr/bin/env bash

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
config_path="${repo_root}/dot_vimrc.tmpl"

assert_contains() {
  local needle="$1"
  if ! rg -F "$needle" "$config_path" >/dev/null; then
    printf 'expected %s to contain: %s\n' "$config_path" "$needle" >&2
    exit 1
  fi
}

assert_contains "function! LoadWalPalette() abort"
assert_contains "function! ApplyWalTheme() abort"
assert_contains "function! RefreshWalThemeIfChanged() abort"
assert_contains "let l:wal_colors_path = expand('~/.cache/wal/colors-wal.vim')"
assert_contains "'mtime': getftime(l:wal_colors_path)"
assert_contains "'raw': l:wal_text"
assert_contains "'bg': matchstr(l:wal_text, 'let color0  = \"\\zs#[0-9A-Fa-f]\\{6}\\ze\"')"
assert_contains "'fg': matchstr(l:wal_text, 'let color7  = \"\\zs#[0-9A-Fa-f]\\{6}\\ze\"')"
assert_contains "'const': matchstr(l:wal_text, 'let color1  = \"\\zs#[0-9A-Fa-f]\\{6}\\ze\"')"
assert_contains "'string': matchstr(l:wal_text, 'let color2  = \"\\zs#[0-9A-Fa-f]\\{6}\\ze\"')"
assert_contains "'type': matchstr(l:wal_text, 'let color3  = \"\\zs#[0-9A-Fa-f]\\{6}\\ze\"')"
assert_contains "'func': matchstr(l:wal_text, 'let color4  = \"\\zs#[0-9A-Fa-f]\\{6}\\ze\"')"
assert_contains "'keyword': matchstr(l:wal_text, 'let color5  = \"\\zs#[0-9A-Fa-f]\\{6}\\ze\"')"
assert_contains "'special': matchstr(l:wal_text, 'let color6  = \"\\zs#[0-9A-Fa-f]\\{6}\\ze\"')"
assert_contains "let l:palette.fingerprint = sha256(l:wal_text)"
assert_contains "highlight Normal ctermbg=0 ctermfg=7"
assert_contains "highlight NormalNC ctermbg=0 ctermfg=7"
assert_contains "highlight EndOfBuffer ctermbg=0 ctermfg=0"
assert_contains "highlight NonText ctermbg=0 ctermfg=0"
assert_contains "highlight LineNr ctermbg=0 ctermfg=8"
assert_contains "highlight CursorLineNr ctermbg=0 ctermfg=8"
assert_contains "highlight FoldColumn ctermbg=0 ctermfg=7"
assert_contains "highlight SignColumn ctermbg=0 ctermfg=4"
assert_contains "highlight Folded ctermbg=0 ctermfg=8"
assert_contains "highlight Comment ctermbg=0 ctermfg=8"
assert_contains "highlight String ctermbg=0 ctermfg=2"
assert_contains "highlight Type ctermbg=0 ctermfg=3"
assert_contains "highlight StorageClass ctermbg=0 ctermfg=3"
assert_contains "highlight Structure ctermbg=0 ctermfg=3"
assert_contains "highlight Typedef ctermbg=0 ctermfg=3"
assert_contains "highlight Function ctermbg=0 ctermfg=4"
assert_contains "highlight Statement ctermbg=0 ctermfg=5"
assert_contains "highlight Label ctermbg=0 ctermfg=5"
assert_contains "highlight Operator ctermbg=0 ctermfg=5"
assert_contains "highlight Special ctermbg=0 ctermfg=6"
assert_contains "highlight Include ctermbg=0 ctermfg=6"
assert_contains "highlight Macro ctermbg=0 ctermfg=6"
assert_contains "highlight PreCondit ctermbg=0 ctermfg=6"
assert_contains "highlight SpecialChar ctermbg=0 ctermfg=6"
assert_contains "highlight Delimiter ctermbg=0 ctermfg=6"
assert_contains "highlight Tag ctermbg=0 ctermfg=6"
assert_contains "guibg=' . l:palette.bg"
assert_contains "guifg=' . l:palette.fg"
assert_contains "highlight! link pythonBuiltin Identifier"
assert_contains "highlight! link pythonBuiltinFunc Function"
assert_contains "highlight! link pythonDecorator PreProc"
assert_contains "highlight! link pythonInclude Include"
assert_contains "highlight! link pythonStatement Statement"
assert_contains "highlight! link pythonOperator Operator"
assert_contains "let g:km_wal_last_mtime = l:palette.mtime"
assert_contains "let g:km_wal_last_fingerprint = l:palette.fingerprint"
assert_contains "silent! colorscheme wal"
assert_contains "function! StartWalThemeWatcher() abort"
assert_contains "let g:km_wal_theme_timer = timer_start(1000, {-> RefreshWalThemeIfChanged()}, {'repeat': -1})"
assert_contains "autocmd ColorScheme wal call ApplyWalTheme()"
assert_contains "autocmd CursorHold,CursorHoldI,FocusGained,VimResume * call RefreshWalThemeIfChanged()"
assert_contains "autocmd VimEnter * call StartWalThemeWatcher()"
assert_contains "set termguicolors"
