#!/usr/bin/env python3
"""Scaffold a runnable LeetCode Python harness from a .txt/.py problem pair."""

from __future__ import annotations

import argparse
import ast
import copy
import difflib
import pprint
import re
import sys
import textwrap
from dataclasses import dataclass
from pathlib import Path
from typing import Any


GENERATED_MARKER = "# Generated by leetcode-init"
EXAMPLE_HEADER_RE = re.compile(r"^Example\s+\d+:", re.IGNORECASE)
ASSIGNMENT_RE = re.compile(r"([A-Za-z_][A-Za-z0-9_]*)\s*=")
GENERIC_SOLUTION_DOCSTRING = "Solve the LeetCode problem for the provided inputs."
VIM_TEXT_WIDTH = 79


@dataclass
class MethodParam:
    """Describe one parameter from the LeetCode solution signature."""
    name: str
    annotation: str
    kind: str


@dataclass
class SolutionSignature:
    """Capture the parsed solution method and preserved implementation details."""
    method_name: str
    params: list[MethodParam]
    return_annotation: str
    return_kind: str
    def_line: str
    method_docstring: str | None
    method_body_lines: list[str] | None


@dataclass
class ExampleCase:
    """Represent one parsed `Example N` block from the prompt text."""
    name: str
    inputs: dict[str, Any]
    expected: Any


@dataclass
class PromptParseResult:
    """Store the cleaned problem summary and parsed example cases."""
    summary: str | None
    examples: list[ExampleCase]


class InitError(Exception):
    """Raised when the script cannot safely scaffold the problem."""


def split_top_level_csv(raw: str) -> list[str]:
    """Split a comma-separated string while respecting nested literals."""
    parts: list[str] = []
    current: list[str] = []
    depth = 0
    in_string: str | None = None
    escape = False

    for char in raw:
        if in_string:
            current.append(char)
            if escape:
                escape = False
            elif char == "\\":
                escape = True
            elif char == in_string:
                in_string = None
            continue

        if char in {"'", '"'}:
            in_string = char
            current.append(char)
            continue

        if char in "([{":
            depth += 1
        elif char in ")]}":
            depth = max(0, depth - 1)

        if char == "," and depth == 0:
            part = "".join(current).strip()
            if part:
                parts.append(part)
            current = []
            continue

        current.append(char)

    tail = "".join(current).strip()
    if tail:
        parts.append(tail)
    return parts


def normalize_literal(raw: str) -> str:
    """Normalize common LeetCode literal spellings into Python syntax."""
    normalized = raw.strip()
    normalized = re.sub(r"\bnull\b", "None", normalized)
    normalized = re.sub(r"\btrue\b", "True", normalized, flags=re.IGNORECASE)
    normalized = re.sub(r"\bfalse\b", "False", normalized, flags=re.IGNORECASE)
    return normalized


def parse_literal(raw: str) -> Any:
    """Parse a prompt literal, falling back to the original scalar text."""
    normalized = normalize_literal(raw)
    try:
        return ast.literal_eval(normalized)
    except (SyntaxError, ValueError):
        stripped = normalized.strip()
        if stripped in {"None", "True", "False"}:
            return ast.literal_eval(stripped)
        if stripped.startswith('"') and stripped.endswith('"'):
            return stripped[1:-1]
        if stripped.startswith("'") and stripped.endswith("'"):
            return stripped[1:-1]
        return stripped


def parse_assignment_map(raw: str) -> dict[str, Any]:
    """Parse `name = value` input assignments from an example block."""
    matches = list(ASSIGNMENT_RE.finditer(raw))
    if not matches:
        raise InitError(f"Could not parse input assignments from: {raw}")

    values: dict[str, Any] = {}
    for index, match in enumerate(matches):
        name = match.group(1)
        value_start = match.end()
        value_end = matches[index + 1].start() if index + 1 < len(matches) else len(raw)
        segment = raw[value_start:value_end].strip().rstrip(",")
        values[name] = parse_literal(segment)
    return values


def extract_problem_summary(text: str) -> str | None:
    """Extract the prompt's problem statement text before the first example."""
    lines = text.splitlines()
    summary_lines: list[str] = []
    capture = False
    started_problem = False

    for raw_line in lines:
        line = raw_line.strip()
        if not line:
            if started_problem and summary_lines and summary_lines[-1] != "":
                summary_lines.append("")
            continue
        if EXAMPLE_HEADER_RE.match(line):
            break
        if line.startswith(("You are given", "Given ", "There is ", "An ", "A ", "Return ", "Design ", "Write ")):
            started_problem = True
        if line in {"Solution", "Python3"}:
            continue
        if line.startswith(("Explore", "Problems", "Contest", "Discuss", "Interview", "Store", "Search")):
            continue
        if line.startswith(("avatar", "Avatar", "Premium", "myList", "notebook", "progress", "points")):
            continue
        if line.startswith(("Orders", "My Playground", "Settings", "Sign out", "Custom Testcase")):
            continue
        if line.startswith(("0", "1", "2", "3")) and len(line) <= 2:
            continue
        if line.startswith("Show Hint"):
            continue
        if line.startswith("class Solution:") or line.startswith("def "):
            continue
        if line.startswith("Back to Chapter"):
            continue
        if not started_problem:
            continue

        capture = True
        summary_lines.append(line)

    while summary_lines and summary_lines[-1] == "":
        summary_lines.pop()
    if not summary_lines:
        return None
    paragraphs: list[str] = []
    current: list[str] = []
    for line in summary_lines:
        if line == "":
            if current:
                paragraphs.append(" ".join(current))
                current = []
            continue
        current.append(line)
    if current:
        paragraphs.append(" ".join(current))
    return "\n\n".join(paragraphs) if paragraphs else None


def parse_examples(text: str) -> list[ExampleCase]:
    """Extract structured example cases from a LeetCode prompt dump."""
    examples: list[ExampleCase] = []
    current_name: str | None = None
    input_lines: list[str] = []
    output_lines: list[str] = []
    collecting: str | None = None

    def flush_current() -> None:
        nonlocal current_name, input_lines, output_lines, collecting
        if current_name and input_lines and output_lines:
            input_text = " ".join(input_lines).strip()
            output_text = " ".join(output_lines).strip()
            examples.append(
                ExampleCase(
                    name=current_name,
                    inputs=parse_assignment_map(input_text),
                    expected=parse_literal(output_text),
                )
            )
        current_name = None
        input_lines = []
        output_lines = []
        collecting = None

    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line:
            continue

        if EXAMPLE_HEADER_RE.match(line):
            flush_current()
            current_name = line.rstrip(":")
            continue

        if current_name is None:
            continue

        if line.startswith("Input:"):
            collecting = "input"
            input_lines = [line[len("Input:") :].strip()]
            continue

        if line.startswith("Output:"):
            collecting = "output"
            output_lines = [line[len("Output:") :].strip()]
            continue

        if re.match(r"^(Explanation|Note|Constraints):", line):
            collecting = None
            continue

        if collecting == "input":
            input_lines.append(line)
        elif collecting == "output":
            output_lines.append(line)

    flush_current()
    if not examples:
        raise InitError("No examples found in the text file.")
    return examples


def parse_prompt(text: str) -> PromptParseResult:
    """Parse the problem summary and structured examples from the prompt dump."""
    return PromptParseResult(summary=extract_problem_summary(text), examples=parse_examples(text))


def detect_kind(annotation: str) -> str:
    """Classify a type annotation into scaffold conversion categories."""
    if "TreeNode" in annotation:
        return "tree"
    if "ListNode" in annotation:
        return "listnode"
    return "plain"


def extract_leading_method_docstring(rest: str) -> str | None:
    """Return the existing method docstring from the stub body, if present."""
    lines = rest.splitlines()
    body_started = False
    doc_lines: list[str] = []
    quote: str | None = None

    for line in lines:
        stripped = line.strip()
        if not stripped:
            continue
        if not line.startswith((" ", "\t")):
            break

        body_started = True
        if quote is not None:
            doc_lines.append(stripped)
            if stripped.endswith(quote) and stripped != quote:
                try:
                    return ast.literal_eval("\n".join(doc_lines))
                except (SyntaxError, ValueError):
                    return None
            continue

        if stripped.startswith('"""') or stripped.startswith("'''"):
            quote = stripped[:3]
            doc_lines = [stripped]
            if stripped.endswith(quote) and len(stripped) >= 6:
                try:
                    return ast.literal_eval(stripped)
                except (SyntaxError, ValueError):
                    return None
            continue

        if body_started:
            return None

    return None


def extract_method_body_lines(rest: str) -> list[str] | None:
    """Capture the existing method body lines after any leading docstring."""
    lines = rest.splitlines()
    body_lines: list[str] = []

    for line in lines:
        if not line.strip():
            if body_lines:
                body_lines.append("")
            continue
        if not line.startswith((" ", "\t")):
            break
        body_lines.append(line)

    while body_lines and body_lines[-1] == "":
        body_lines.pop()

    if not body_lines:
        return None

    if body_lines[0].strip().startswith('"""') or body_lines[0].strip().startswith("'''"):
        delimiter = body_lines[0].strip()[:3]
        index = 0
        if not (body_lines[0].strip().endswith(delimiter) and len(body_lines[0].strip()) >= 6):
            index = 1
            while index < len(body_lines):
                if body_lines[index].strip().endswith(delimiter):
                    index += 1
                    break
                index += 1
        else:
            index = 1
        body_lines = body_lines[index:]

    while body_lines and not body_lines[0].strip():
        body_lines.pop(0)

    return body_lines or None


def parse_signature(python_text: str) -> SolutionSignature:
    """Parse the `Solution` method signature and any preserved method content."""
    class_match = re.search(r"(?m)^class\s+Solution\s*:\s*$", python_text)
    if not class_match:
        raise InitError("Could not find `class Solution:` in the Python file.")

    rest = python_text[class_match.end() :]
    match = re.search(
        r"(?m)^(\s*def\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(([^)]*)\)\s*(?:->\s*([^:]+))?:\s*)$",
        rest,
    )
    if not match:
        raise InitError("Could not find a Solution method signature to scaffold.")

    params_raw = match.group(3).strip()
    params: list[MethodParam] = []
    for part in split_top_level_csv(params_raw):
        if part == "self":
            continue
        name_and_type = part.split("=", 1)[0].strip()
        if ":" in name_and_type:
            name, annotation = name_and_type.split(":", 1)
            param_name = name.strip()
            param_annotation = annotation.strip()
        else:
            param_name = name_and_type.strip()
            param_annotation = "Any"
        params.append(
            MethodParam(
                name=param_name,
                annotation=param_annotation,
                kind=detect_kind(param_annotation),
            )
        )

    return_annotation = (match.group(4) or "Any").strip()
    return SolutionSignature(
        method_name=match.group(2),
        params=params,
        return_annotation=return_annotation,
        return_kind=detect_kind(return_annotation),
        def_line=match.group(1).strip(),
        method_docstring=extract_leading_method_docstring(rest[match.end() :]),
        method_body_lines=extract_method_body_lines(rest[match.end() :]),
    )


def is_safe_to_rewrite(python_text: str) -> bool:
    """Allow rewrites only for stubs or previously generated scaffolds."""
    if GENERATED_MARKER in python_text:
        return True
    lines = python_text.splitlines()
    in_method = False
    method_indent = 0
    inside_docstring = False
    docstring_delimiter: str | None = None
    saw_body_statement = False

    for line in lines:
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith("#"):
            continue
        if stripped.startswith(("from ", "import ")):
            continue
        if re.match(r"^class\s+Solution\s*:\s*$", stripped):
            continue
        if re.match(r"^def\s+[A-Za-z_][A-Za-z0-9_]*\s*\(", stripped):
            in_method = True
            method_indent = len(line) - len(line.lstrip(" "))
            inside_docstring = False
            docstring_delimiter = None
            saw_body_statement = False
            continue
        if not in_method:
            return False

        indent = len(line) - len(line.lstrip(" "))
        if indent <= method_indent:
            return False

        if inside_docstring:
            if stripped.endswith(docstring_delimiter or ""):
                inside_docstring = False
                docstring_delimiter = None
            continue

        if not saw_body_statement and (stripped.startswith('"""') or stripped.startswith("'''")):
            saw_body_statement = True
            delimiter = stripped[:3]
            if not (stripped.endswith(delimiter) and len(stripped) >= 6):
                inside_docstring = True
                docstring_delimiter = delimiter
            continue

        saw_body_statement = True
        if stripped in {"pass", "..."}:
            continue
        if stripped.startswith("raise NotImplementedError"):
            continue
        return False

    return in_method and not inside_docstring


def render_method_docstring(docstring: str | None) -> str:
    """Render a method docstring block with scaffold indentation."""
    content = docstring or GENERIC_SOLUTION_DOCSTRING
    escaped = content.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
    lines: list[str] = []
    wrap_width = max(20, VIM_TEXT_WIDTH - 8)
    for raw_line in escaped.splitlines() or [escaped]:
        if not raw_line:
            lines.append("")
            continue
        if raw_line in {"Examples:"} or raw_line.startswith("Example "):
            lines.append(raw_line)
            continue
        initial_indent = ""
        subsequent_indent = ""
        if raw_line.startswith("Input: "):
            initial_indent = "Input: "
            subsequent_indent = " " * len(initial_indent)
            raw_line = raw_line[len(initial_indent) :]
        elif raw_line.startswith("Output: "):
            initial_indent = "Output: "
            subsequent_indent = " " * len(initial_indent)
            raw_line = raw_line[len(initial_indent) :]
        lines.extend(
            textwrap.wrap(
                raw_line,
                width=wrap_width,
                initial_indent=initial_indent,
                subsequent_indent=subsequent_indent,
                break_long_words=False,
                break_on_hyphens=False,
            )
            or [initial_indent.rstrip()]
        )
    if len(lines) == 1:
        return f'        """{lines[0]}"""'
    rendered = ['        """']
    rendered.extend(f"        {line}" for line in lines)
    rendered.append('        """')
    return "\n".join(rendered)


def build_examples_docstring(summary: str | None, examples: list[ExampleCase]) -> str:
    """Build a default solution docstring from the summary and parsed examples."""
    lines: list[str] = []
    if summary:
        lines.extend(summary.splitlines())
        lines.append("")
    lines.append("Examples:")
    for example in examples:
        inputs = ", ".join(
            f"{name} = {pprint.pformat(value, sort_dicts=False, width=88)}"
            for name, value in example.inputs.items()
        )
        output = pprint.pformat(example.expected, sort_dicts=False, width=88)
        lines.append("")
        lines.append(example.name)
        lines.append(f"Input: {inputs}")
        lines.append(f"Output: {output}")
    return "\n".join(lines)


def should_preserve_method_docstring(docstring: str | None) -> bool:
    """Keep only user-authored solution docstrings during regeneration."""
    if not docstring:
        return False
    normalized = docstring.strip()
    if normalized == GENERIC_SOLUTION_DOCSTRING:
        return False
    if normalized.startswith("Examples:"):
        return False
    return True


def render_method_body(signature: SolutionSignature) -> str:
    """Render the preserved method body or the default placeholder raise."""
    if signature.method_body_lines:
        return "\n".join(signature.method_body_lines)
    return f'        raise NotImplementedError("Implement {signature.method_name} before running this scaffold.")'


def resolve_pair(target: str | None, cwd: Path) -> tuple[Path, Path]:
    """Resolve a target slug or path into matching `.py` and `.txt` files."""
    if target is None:
        py_files = sorted(path for path in cwd.glob("*.py") if path.with_suffix(".txt").exists())
        if len(py_files) != 1:
            raise InitError("Expected exactly one same-name .py/.txt pair in the current directory.")
        python_path = py_files[0]
        return python_path, python_path.with_suffix(".txt")

    raw_target = Path(target).expanduser()
    if raw_target.exists():
        resolved = raw_target.resolve()
        if resolved.is_dir():
            return resolve_pair(None, resolved)
        if resolved.suffix == ".py":
            return resolved, resolved.with_suffix(".txt")
        if resolved.suffix == ".txt":
            return resolved.with_suffix(".py"), resolved

    slug = raw_target.stem if raw_target.suffix else raw_target.name
    python_path = (cwd / f"{slug}.py").resolve()
    text_path = (cwd / f"{slug}.txt").resolve()
    return python_path, text_path


def render_examples_literal(examples: list[ExampleCase]) -> str:
    """Serialize parsed examples into stable Python source."""
    payload = [
        {"name": example.name, "input": example.inputs, "expected": example.expected}
        for example in examples
    ]
    return pprint.pformat(payload, sort_dicts=False, width=88)


def render_tree_helpers() -> str:
    """Return scaffold helpers for tree-based LeetCode problems."""
    return """
class TreeNode:
    \"\"\"Create a binary tree node used by LeetCode examples.\"\"\"

    def __init__(self, val: int = 0, left: Optional[TreeNode] = None, right: Optional[TreeNode] = None):
        self.val = val
        self.left = left
        self.right = right


def build_tree(values: list[Any] | None) -> Optional[TreeNode]:
    \"\"\"Build a binary tree from LeetCode level-order list data.\"\"\"
    if not values:
        return None
    nodes = [None if value is None else TreeNode(value) for value in values]
    kids = nodes[::-1]
    root = kids.pop()
    for node in nodes:
        if node is None:
            continue
        if kids:
            node.left = kids.pop()
        if kids:
            node.right = kids.pop()
    return root


def serialize_tree(root: Optional[TreeNode]) -> list[Any]:
    \"\"\"Convert a binary tree back into LeetCode level-order list data.\"\"\"
    if root is None:
        return []
    values: list[Any] = []
    queue: deque[Optional[TreeNode]] = deque([root])
    while queue:
        node = queue.popleft()
        if node is None:
            values.append(None)
            continue
        values.append(node.val)
        queue.append(node.left)
        queue.append(node.right)
    while values and values[-1] is None:
        values.pop()
    return values
""".strip()


def render_list_helpers() -> str:
    """Return scaffold helpers for linked-list LeetCode problems."""
    return """
class ListNode:
    \"\"\"Create a linked-list node used by LeetCode examples.\"\"\"

    def __init__(self, val: int = 0, next: Optional[ListNode] = None):
        self.val = val
        self.next = next


def build_linked_list(values: list[Any] | None) -> Optional[ListNode]:
    \"\"\"Build a linked list from LeetCode list input data.\"\"\"
    if not values:
        return None
    dummy = ListNode()
    tail = dummy
    for value in values:
        tail.next = ListNode(value)
        tail = tail.next
    return dummy.next


def serialize_linked_list(head: Optional[ListNode]) -> list[Any]:
    \"\"\"Convert a linked list back into plain Python list data.\"\"\"
    values: list[Any] = []
    seen = 0
    current = head
    while current is not None:
        values.append(current.val)
        current = current.next
        seen += 1
        if seen > 10_000:
            raise RuntimeError("Linked list serialization exceeded safety limit.")
    return values
""".strip()


def build_generated_source(
    signature: SolutionSignature, summary: str | None, examples: list[ExampleCase]
) -> str:
    """Build the full scaffolded Python source for a problem pair."""
    needs_tree = any(param.kind == "tree" for param in signature.params) or signature.return_kind == "tree"
    needs_list = any(param.kind == "listnode" for param in signature.params) or signature.return_kind == "listnode"

    imports = [
        "from __future__ import annotations",
        "",
        "import argparse",
        "import copy",
        "import difflib",
        "import pprint",
        "import unittest",
    ]
    if needs_tree:
        imports.append("from collections import deque")
    imports.extend(
        [
            "from typing import Any, List, Optional",
            "",
            "",
            GENERATED_MARKER,
            "",
        ]
    )

    helper_sections: list[str] = []
    if needs_tree:
        helper_sections.append(render_tree_helpers())
    if needs_list:
        helper_sections.append(render_list_helpers())

    param_kinds = pprint.pformat(
        {param.name: param.kind for param in signature.params},
        sort_dicts=False,
        width=88,
    )
    param_order = pprint.pformat([param.name for param in signature.params], width=88)
    examples_literal = render_examples_literal(examples)

    body_sections = [
        "\n".join(imports),
        *helper_sections,
        f"""
class Solution:
    {signature.def_line}
{render_method_docstring(signature.method_docstring if should_preserve_method_docstring(signature.method_docstring) else build_examples_docstring(summary, examples))}
{render_method_body(signature)}
""".strip(),
        f"""
PARAM_ORDER = {param_order}
PARAM_KINDS = {param_kinds}
RETURN_KIND = {signature.return_kind!r}
EXAMPLES = {examples_literal}


def prepare_argument(name: str, value: Any) -> Any:
    \"\"\"Convert one stored example input into the expected runtime value.\"\"\"
    kind = PARAM_KINDS[name]
    if kind == "tree":
        return build_tree(copy.deepcopy(value))
    if kind == "listnode":
        return build_linked_list(copy.deepcopy(value))
    return copy.deepcopy(value)


def normalize_result(value: Any) -> Any:
    \"\"\"Normalize a solution result back into comparable plain data.\"\"\"
    if RETURN_KIND == "tree":
        return serialize_tree(value)
    if RETURN_KIND == "listnode":
        return serialize_linked_list(value)
    return value


def format_diff(expected: Any, actual: Any) -> str:
    \"\"\"Render a unified diff for mismatched expected and actual values.\"\"\"
    expected_lines = pprint.pformat(expected, sort_dicts=False).splitlines()
    actual_lines = pprint.pformat(actual, sort_dicts=False).splitlines()
    diff = list(
        difflib.unified_diff(
            expected_lines,
            actual_lines,
            fromfile="expected",
            tofile="actual",
            lineterm="",
        )
    )
    return "\\n".join(diff) if diff else "No diff."


def run_case(case: dict[str, Any]) -> tuple[Any, Any, str | None]:
    \"\"\"Execute one example case and capture any failure mode.\"\"\"
    solution = Solution()
    prepared_args = [prepare_argument(name, case["input"][name]) for name in PARAM_ORDER]
    try:
        actual = solution.{signature.method_name}(*prepared_args)
    except NotImplementedError as exc:
        return case["expected"], f"<not implemented: {{exc}}>", "not_implemented"
    except Exception as exc:  # pragma: no cover - surfaced to the caller for debugging.
        label = f"{{exc.__class__.__name__}}: {{exc}}"
        return case["expected"], f"<exception: {{label}}>", "exception"
    return case["expected"], normalize_result(actual), None


def run_examples() -> None:
    \"\"\"Print each parsed example and compare it against the current solution.\"\"\"
    for case in EXAMPLES:
        expected, actual, error = run_case(case)
        matched = error is None and actual == expected
        print(case["name"])
        print(f"Input: {{case['input']!r}}")
        print(f"Expected: {{expected!r}}")
        print(f"Actual: {{actual!r}}")
        print(f"Matches expected: {{matched}}")
        if error is not None or not matched:
            print("Diff:")
            print(format_diff(expected, actual))
        print()


class GeneratedExampleTests(unittest.TestCase):
    def test_examples(self) -> None:
        \"\"\"Assert that every parsed example matches the current solution output.\"\"\"
        for case in EXAMPLES:
            with self.subTest(example=case["name"]):
                expected, actual, error = run_case(case)
                if error == "not_implemented":
                    self.fail(f"Solution not implemented for {{case['name']}}: {{actual}}")
                if error == "exception":
                    self.fail(f"Solution raised an exception for {{case['name']}}: {{actual}}")
                self.assertEqual(expected, actual, format_diff(expected, actual))


def main() -> None:
    \"\"\"Run the generated CLI entrypoint for examples or unittest mode.\"\"\"
    parser = argparse.ArgumentParser(description="Run the generated LeetCode scaffold.")
    parser.add_argument("--test", action="store_true", help="Run unittest checks instead of the example runner.")
    args = parser.parse_args()
    if args.test:
        unittest.main(argv=[sys.argv[0]])
        return
    run_examples()


if __name__ == "__main__":
    main()
""".strip(),
    ]
    return "\n\n\n".join(section for section in body_sections if section).rstrip() + "\n"


def scaffold_problem(target: str | None, cwd: Path) -> tuple[Path, str]:
    """Rewrite a problem stub into a runnable scaffold and return its diff."""
    python_path, text_path = resolve_pair(target, cwd)
    if not python_path.exists():
        raise InitError(f"Missing Python file: {python_path}")
    if not text_path.exists():
        raise InitError(f"Missing text file: {text_path}")

    python_text = python_path.read_text(encoding="utf-8")
    if not is_safe_to_rewrite(python_text):
        raise InitError(f"Refusing to overwrite non-stub solution file: {python_path}")

    signature = parse_signature(python_text)
    prompt = parse_prompt(text_path.read_text(encoding="utf-8"))
    generated = build_generated_source(signature, prompt.summary, prompt.examples)
    old_lines = python_text.splitlines()
    new_lines = generated.splitlines()
    diff = "\n".join(
        difflib.unified_diff(
            old_lines,
            new_lines,
            fromfile=str(python_path),
            tofile=str(python_path),
            lineterm="",
        )
    )
    python_path.write_text(generated, encoding="utf-8")
    return python_path, diff


def main() -> int:
    """Run the CLI entrypoint for scaffolding a LeetCode problem locally."""
    parser = argparse.ArgumentParser(
        description="Scaffold a LeetCode Python harness from a same-name .txt and .py pair.",
    )
    parser.add_argument(
        "target",
        nargs="?",
        help="Problem slug, .py/.txt path, or directory containing exactly one same-name pair.",
    )
    args = parser.parse_args()

    try:
        python_path, diff = scaffold_problem(args.target, Path.cwd())
    except InitError as exc:
        print(str(exc), file=sys.stderr)
        return 1

    if diff:
        print(diff)
    else:
        print(f"No changes required for {python_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
