#!/usr/bin/env bash

set -euo pipefail

xrandr \
  --output DVI-D-0 --mode 2048x1152 --pos 0x0 --rotate normal \
  --output DP-2 --mode 3840x2160 --pos 2048x0 --rotate normal \
  --output HDMI-0 --mode 1920x1080 --pos 5888x0 --rotate normal \
  --output HDMI-1 --off \
  --output DP-0 --off \
  --output DP-1 --off \
  --output DP-3 --off
